# Generated by Django 5.0.1 on 2024-01-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_quality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
